spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Manikantaaj/microservice-architecture.git
          searchPaths: microservice-config/api-gateway, microservice-config/config-service
        bootstrap: true

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
